import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navigation-bar/NavBar";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Bistatechnologies Next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html >
  );
}
